# Generated by Django 3.2 on 2021-07-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_instructor_course_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='instructor',
        ),
    ]
